### ISSUE TITLE
XbrlApi Reference

### ISSUE THREAD

**Issue by bbkrr** [janlukasschroeder/sec-api-python#1]
I think you need to add XbrlApi in your __init__.py for the latest update.

While importing xbrlApi, it is throwing an error.

`ImportError: cannot import name 'XbrlApi' from 'sec_api'`

https://github.com/janlukasschroeder/sec-api-python/blob/38042fd00379c6e03e0e57154831cad83168d91c/sec_api/__init__.py#L1-L4

**Comment by janlukasschroeder** [comment]
great pickup, thanks! that's fixed now and the new version 1.0.6 is published
