### ISSUE TITLE
Timeout on requests

### ISSUE THREAD

**Issue by SamStephens** [janlukasschroeder/sec-api-python#11]
All usages of requests are done without a timeout ([for example here is the QueryApi request](https://github.com/janlukasschroeder/sec-api-python/blob/61cb1e0f31b95b04b44bd12e94a9a284acd9e5b9/sec_api/index.py#L55-L57)). As per [the requests documentation](https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts), "Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely".

I'm making requests from AWS Lambda. What I'm encountering is that sporadically my Lambda hangs until it times out. I'm not sure what the cause is, but if I was getting `requests.exceptions.Timeout` thrown from requests, I'd be able to retry the request after a timeout.

**Comment by janlukasschroeder** [comment]
Absolutely. Refer to https://github.com/janlukasschroeder/sec-api-python/issues/12
