### ISSUE TITLE
Ability to disable default retry strategy

### ISSUE THREAD

**Issue by SamStephens** [janlukasschroeder/sec-api-python#12]
The SDK provides a default retry strategy ([for example here is the QueryApi request](https://github.com/janlukasschroeder/sec-api-python/blob/61cb1e0f31b95b04b44bd12e94a9a284acd9e5b9/sec_api/index.py#L53-L66)). Whilst it is nice this is provided, it would be useful to be able to disable the default retry strategy for users who want to provide their own.

There's a few reasons users might want provide their own retry strategy. One is that they may have retry conditions not included in the default strategy. For example, [I'd like to be able to retry timed out requests](https://github.com/janlukasschroeder/sec-api-python/issues/11). People may be using the library from a flaky networking setup where they need to retry connection resets.

Another reason is to change the backoff configuration. If people can bring their own retry strategy, they can introduce jitter ([here's an AWS blog on why jitter is a exponential backoff best practice](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)). They may wish to retry more times.

**Comment by janlukasschroeder** [comment]
Interesting idea. From our experience with clients, we typically see two cases: 
A) As you said, the default backoff strategy is sufficient in 99% of the time
B) A custom backoff strat is required. In such cases, clients typically want to implement the wrapper themselves rather than adjusting our wrapper.
