### ISSUE TITLE
Consider providing API Key as header rather than query parameter

### ISSUE THREAD

**Issue by SamStephens** [janlukasschroeder/sec-api-python#13]
As per https://sec-api.io/docs/query-api#authentication, the API Key can be provided as either a header or a query parameter. [The API currently uses a query parameter](https://github.com/janlukasschroeder/sec-api-python/blob/61cb1e0f31b95b04b44bd12e94a9a284acd9e5b9/sec_api/index.py#L47).

Please consider switching to a header. URLs can end up going through proxies, scanning engines, and all sorts of entities that should not see a secret like an API Key. Headers are much less likely to be accidentally exposed.

**Comment by janlukasschroeder** [comment]
Absolutely agree from a security point of view. However, some use cases require the `token` parameter. For example, various clients are running scripts behind an internal company firewall blocking requests with `Authorization` headers and the only option to authenticate requests is via the `token` query parameter.

**Comment by SamStephens** [comment]
@janlukasschroeder thanks. Would you consider making this configurable (use header by default, and token parameter if configured for users who need it)? It's a dealbreaker for using this library for me.

>For example, various clients are running scripts behind an internal company firewall blocking requests with Authorization headers 

That's pretty unfortunate 🙄
