### ISSUE TITLE
QueryAPI won't find every filing

### ISSUE THREAD

**Issue by Freddy19911** [janlukasschroeder/sec-api-python#2]
I have noticed that the QueryApi seems to ignore some filings when I am looking for the DEF 14A filing. 

```
from sec_api import QueryApi

queryApi = QueryApi(api_key="MY-API-KEY")

query = {
  "query": { "query_string": { 
      "query": "cik:896878 AND filedAt:{2001-01-01 TO 2001-12-31} AND formType:\"DEF 14A\"" 
    } },
  "from": "0",
  "size": "10",
  "sort": [{ "filedAt": { "order": "desc" } }]
}

filings = queryApi.get_filings(query)

print(filings)
```

In the example, the company 896878 filed a DEF 14A on the 2001-11-29 but the API somehow won't find it. 
If I extend the time period from 2000-01-01 TO 2005-12-31, the API only finds the DEF 14A  for the years 2000, 2002, 2004 and 2005 even though there is a filing for every year in EDGAR.

**Comment by janlukasschroeder** [comment]
Thanks for bringing this to our attention. We'll look into this straight away.

**Comment by Freddy19911** [comment]
Other filings seems to be affected as well. When I query the 10-K for Microsoft (789019) between 2000-01-01 to 2020-12-31 it will ignore the filings for the years 2001, 2003, 2013, 2014.
