### ISSUE TITLE
extractorApi gives "504 Gateway Time-out"

### ISSUE THREAD

**Issue by kvtoraman** [janlukasschroeder/sec-api-python#3]
I've tried extractorApi and got `504 Gateway Time-out` for some of the URLs. Here are two URLs that you can reproduce this:

https://www.sec.gov/Archives/edgar/data/1179929/000117992920000026/moh-12312019x10k.htm
https://www.sec.gov/Archives/edgar/data/831001/000083100120000031/c-12312019x10k.htm

Here is an example query:
```python
extractorApi.get_section("https://www.sec.gov/Archives/edgar/data/1179929/000117992920000026/moh-12312019x10k.htm", "1", "text")
```
I checked both of these filings and they don't follow the generic 10-K format. So I would understand if they are harder to parse.

**Comment by janlukasschroeder** [comment]
> So I would understand if they are harder to parse.

Yes, correct - that's the reason. The filings you found don't have an heuristically parsable structure. We'll check how we can cover such edge cases. Thanks for sharing the links.

We'll also add better error handling to let you know next time what happened.
