### ISSUE TITLE
Flipped "linkToHtml" and "linkToFilingDetails"

### ISSUE THREAD

**Issue by LukeDickerson19** [janlukasschroeder/sec-api-python#4]
The "linkToHtml" and "linkToFilingDetails" links seem to be flipped. For example, in your browser go to the "linkToHtml" and "linkToFilingDetails" urls of the first "filing" in the results of the example query here: https://sec-api.io/sandbox/apple-sec-filings
You will see that the url for "linkToFilingDetails" is actually the HTML link and the "linkToHtml" is actually the Filing Details link.

**Comment by janlukasschroeder** [comment]
@PopeyedLocket thanks. that's the correct behavior. "linkToHtml" points to the "index.html" page of the filing and "linkToFilingDetails" points to the details (in other words the filing content) of the filing.
